/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the 
 * following formulae:
 *
 * Triangle         Tn=n(n+1)/2     1, 3,  6, 10, 15, ...
 * Pentagonal       Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
 * Hexagonal        Hn=n(2n-1)      1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

def triangle(n:Long) : Long = n*(n+1)/2
def pentagonal(n:Long) : Long = n*(3*n-1)/2
def hexagonal(n:Long) : Long = n*(2*n-1)

var res = 0L
var h   = 0L
var p   = 0L
var hi  = 144
var pi  = 166
var ti  = 286

while (res == 0) {
  h = hexagonal(hi)
  p = pentagonal(pi)

  if (h == p) {
    if (triangle(ti) == h) res = h
    else ti += 1
    res = h
  }
  else if (p < h) pi += 1
  else hi += 1
}

println(res)
